### PR TITLE
Tutorial for creating new built-in datasets

### PR DESCRIPTION
**Pull request by vdumoulin**
After this is merged, I think we'll be able to delegate adding / refactoring built-in datasets much more easily.

### CODE REVIEW

**Comment by vdumoulin** [comment]
@bartvm @dwf With this tutorial, I think we'll have all we need to start assigning the task of refactoring an existing built-in dataset or add a new commonly-used dataset to Fuel.

**Comment by bartvm** [comment]
Looks good to me! The only thing I would consider adding is basically turning the entire tutorial in a series of unit tests (basically just copy and paste the tutorial I guess?). However, we can refer that to a later date if you prefer merging this soon.

**Comment by vdumoulin** [comment]
I'd prefer merging sooner. I'll create an issue for that.

**Comment by vdumoulin** [comment]
I opened the issue (#87) for the unit tests, I'll merge now and we'll address this later.

**Pull request merged**
