### PR TITLE
Better converter errors on non-existent files.

### PR DESCRIPTION
**Pull request by dwf**
@vdumoulin

### CODE REVIEW

**Comment by dwf** [comment]
Fixed + squashed the typo from before.

**Comment by vdumoulin** [comment]
I'm hesitant on being too strict, but could you make sure that what you introduced is covered by a unit test?

**Comment by dwf** [comment]
@vdumoulin 95e1511

**Comment by dwf** [comment]
Woopsie, need `from __future__ import print_function`.  cd1d750

**Comment by dwf** [comment]
On second thought, squashed as 96302f7.

**Comment by vdumoulin** [comment]
vdumoulin's seal of approval

**Pull request merged**
