### PR TITLE
Test coverage improvements

### PR DESCRIPTION
**Pull request by vdumoulin**
Test coverage was dropping pretty fast, so I figured I'd do something about it.

It's still work in progress, but it may be a good idea to merge it in its current state (this PR is already getting quite big to review, sorry about that!) and continue in another PR.

### CODE REVIEW

**Comment by vdumoulin** [comment]
General tip to whoever will review this PR: it may be faster to review it commit by commit, as I didn't do lots of back-and-forth edits between commits and they're incremental.

**Comment by bartvm** [comment]
Looks good to me at first sight, but I have to say that towards the end of the PR I found myself skimming more than reading... I'll try and give it a second pass later today.

**Comment by vdumoulin** [comment]
Thanks a lot for having a look! @dwf also said he'd give it a look.

**Comment by dwf** [comment]
So I think my comments boil down to two major things:
* Tempfile module where appropriate 
* Use
```python
args_dict = vars(args)
args_dict.pop('func')
args.func(**args_dict)
```

and 

```python
def my_converter(foo, bar, baz):
    ...
```
rather than
```python
args.func(args)
```
and
```python
def my_converter(args):
    foo = args.foo
    bar = args.bar
    baz = args.baz
```

**Comment by vdumoulin** [comment]
@dwf I addressed your comments in the four most recent commits. Let's wait and see what Travis has to say.

**Comment by dwf** [comment]
LGTM. I don't see any reason not to merge.

**Pull request merged**
