### PR TITLE
Add CIFAR10 dataset

### PR DESCRIPTION
**Pull request by vdumoulin**
Based off `MNIST`, uses data that can currently be obtained through Pylearn2's `download_cifar10.sh` script.

### CODE REVIEW

**Comment by bartvm** [comment]
Tests are just failing right now because the data is missing on Travis. I think we can add that as with MNIST (we can store it in the cache in Travis's new container environment so that it doesn't need to be redownloaded each time).

I'll make a ticket though, because I feel that there is a lot of code duplication between this and MNIST, and there's a variety of things that could be factored out for use by future datasets as well.

**Comment by vdumoulin** [comment]
@bartvm Even though I think I've properly added the CIFAR10 files to cache, the tests fail. I'm not very Travis-savvy, is there something I left out?

**Comment by bartvm** [comment]
On my phone, but the log says:

tar: Old option `f' requires an argument.
Try `tar --help' or `tar --usage' for more information.

Maybe there's something wrong with the Tar command so that it doesn't actually unpack?

**Comment by bartvm** [comment]
On my phone, but the log says:

tar: Old option `f' requires an argument.
Try `tar --help' or `tar --usage' for more information.

Maybe there's something wrong with the Tar command so that it doesn't actually unpack?

**Comment by vdumoulin** [comment]
I think I found what the issue was, but I can't fix it since I don't think I can clear the cache by myself.

**Comment by bartvm** [comment]
I think the bash command still doesn't fully work. The problem is that `curl -O` doesn't write to `stdout`, but to a file instead. Also, `tar f` requires you to give a filename to read from, but in this case you want to read from `stdin` for which you need to pass `-`. I think the final command should look like this:
```bash
curl http://www.cs.utoronto.ca/~kriz/cifar-10-python.tar.gz | tar xzf -
```

**Comment by vdumoulin** [comment]
Yes, I think you're right. I gleaned the command from the Pylearn2 script, but I missed the dash at the end of the `tar` command. There's also apparently a way to use the same trick with `curl -O` which is present in the original command:

```
curl -O http://www.cs.utoronto.ca/~kriz/cifar-10-python.tar.gz - | tar xvzf -
```

I'll try to push a commit to force resetting the cache properly, and if it works I'll squash all commits related to fixing my mistake.

**Comment by vdumoulin** [comment]
@bartvm I wasn't able to repair my cache mistake. I put the right `curl` command and cleaned up the commits, but I think removing `cifar10` from the cache will require manual intervention.

Sorry about that!

**Comment by bartvm** [comment]
No problem! I cleared the cache manually and restarted the build

**Comment by bartvm** [comment]
Python 2 passes now, but you should use `from six.moves import cPickle` for Python 3 compatibility.

**Comment by vdumoulin** [comment]
@bartvm Yes! For `xrange` as well. I'm on it.

**Comment by bartvm** [comment]
Try opening it with mode `'rb'`, for Python 3 refuses to cast automatically between string- and byte-encoded data.

**Comment by bartvm** [comment]
Sorry, my bad, I only just realised you were trying to unpickle the file that you downloaded, which I guess was pickled with Python 2... They use different encoding schemes, but this could work:
```python
cPickle.load(f, encoding='latin1')
```

**Comment by vdumoulin** [comment]
That will fail under Python 2, since `cPickle` doesn't accept the `encoding` argument.

**Comment by vdumoulin** [comment]
One option would be this:

```python
try:
    data = cPickle.load(f, encoding='latin1')
except TypeError:
    data = cPickle.load(f)
```

but it isn't very readable in my opinion.

**Comment by bartvm** [comment]
I agree, but you can use `if six.PY3:` which is okay I think.

**Comment by vdumoulin** [comment]
@bartvm Thanks for the tip. The tests now pass.

**Pull request merged**
