### PR TITLE
Add tutorial for H5PYDataset class

### PR DESCRIPTION
**Pull request by vdumoulin**

### CODE REVIEW

**Comment by bartvm** [comment]
Oh damn, that doctest issue with unicode literals is annoying. You can just skip it if you want, or if you feel adventurous, here's how to fix it: https://dirkjan.ochtman.nl/writing/2014/07/06/single-source-python-23-doctests.html

**Comment by vdumoulin** [comment]
I'll skip it, it's not particularly crucial since `H5PYDataset` is already somewhat under unit tests.

**Comment by vdumoulin** [comment]
I don't get how the code coverage can decrease if all I've added is documentation... oh well!

**Comment by bartvm** [comment]
https://github.com/bartvm/blocks/pull/468#issuecomment-81171808

**Comment by vdumoulin** [comment]
Would you like me to rebase just to be on the safe side?

**Comment by bartvm** [comment]
No need, it's obvious that this PR can only increase coverage.

**Pull request merged**
