### PR TITLE
Changed H5PYDataset to enable sharing file handles and fix serialization

### PR DESCRIPTION
**Pull request by jfsantos**
This is a tentative implementation to fix the issues reported in #65. The "state" for an out-of-memory H5PYDataset is now just the HDF5 file name, and the class will share a handle to that file as long as there is someone accessing it (ref_counts for that handle >  1).

### CODE REVIEW

**Comment by vdumoulin** [comment]
@jfsantos Would you mind rebasing your code on top of `master`? I'll have a look at it afterwards.

**Comment by jfsantos** [comment]
My fix was a bit messy, so maybe it's better to think on another way of solving this. The big thing is that `DataStream` can't use anything coming from h5py (neither the handle nor the file id) as a state, since the `DataStream` instance is going to be serialized with the main loop and it keeps the state as an instance attribute. Maybe one way would be simply keeping the handle in a dictionary in H5PYDataset (as a class attribute) and pass the filepath or a hash of the handle object as a state.

**Comment by dwf** [comment]
I doubt the hash would be preserved across interpreter sessions, if that is
the desired behaviour.

**Comment by jfsantos** [comment]
You are right. Maybe the filename would be the safest bet?

**Comment by vdumoulin** [comment]
I think you found the right solution, I'd just polish it a little more. How about this:

* The `state` passed around is a file path (using the full path for uniqueness).
* We maintain a private `_ref_counts` class attribute which is a `dict` mapping file paths to reference counts.
* We also maintain a private `_file_handles` class attribute which is a `dict` mapping file paths to HDF5 file handles.
* We implement `get_file_handle` and `release_file_handle` class methods which are responsible for maintaining the state of `_ref_counts` and `_file_handles`.

**Comment by vdumoulin** [comment]
Also, if you're able to come up with a minimal bug-reproducing example we should make a unit test out of that.

**Comment by jfsantos** [comment]
I'll go ahead and close this since the issue was fixed by #100

**Comment by vdumoulin** [comment]
Good, thanks again for pointing out the issue!

**Pull request closed without merging**
